/** Wonder WooCommerce Quick View Trial
 * Copyright 2019 Magic Hills Pty Ltd All Rights Reserved
 * Website: http://www.wonderplugin.com
 * Version 2.5 
 */
(function($){$(document).ready(function(){(function initQuickView(){var isTouch="ontouchstart"in window||window.DocumentTouch&&document instanceof DocumentTouch;var options={quickviewpos:"overimage",overimagepos:"center",showonhover:1,alwaysshowontouch:1,viewcartnewtab:0,closeafteraddtocart:0};if($("#wonderwooquickview_options").length>0)$.each($("#wonderwooquickview_options").data(),function(key,value){options[key.toLowerCase()]=value});var adjustButtonPos=function(){$(".wonder-wooquickview-button").each(function(){var button=
$(this);var img=button.closest(".product").find("img");if(img.length>0){var h=img.height();if(h>0)if(options.overimagepos=="bottomleft")button.css({left:0,right:"auto",top:h+"px",transform:"translateY(-100%)"});else if(options.overimagepos=="bottomright")button.css({left:"auto",right:0,top:h+"px",transform:"translateY(-100%)"});else button.css({left:"50%",right:"auto",top:h/2+"px",transform:"translateX(-50%) translateY(-50%)"})}})};var addButtonOverImage=function(){if(options.quickviewpos=="overimage"){$(".wonder-wooquickview-button").css({position:"absolute",
bottom:"auto"});if(options.overimagepos=="topleft")$(".wonder-wooquickview-button").css({top:0,left:0,right:"auto"});else if(options.overimagepos=="topright")$(".wonder-wooquickview-button").css({top:0,left:"auto",right:0});else{adjustButtonPos();$(window).on("resize orientationchange",function(){adjustButtonPos()})}if(!options.showonhover)$(".wonder-wooquickview-button").show();else if(isTouch&&options.alwaysshowontouch)$(".wonder-wooquickview-button").show();else{$(".wonder-wooquickview-button").css({display:"block",
opacity:0});$(".wonder-wooquickview-button").each(function(){var button=$(this);var product=button.closest(".product");if(product.length>0)product.hover(function(){button.css({opacity:1})},function(){button.css({opacity:0})})})}}};addButtonOverImage();var ajaxAddToCart=function(){$(document).on("click",".wonder-wooquickview-content .wonder-wooquickview-addtocart-ajax .single_add_to_cart_button:not(.disabled)",function(event){event.preventDefault();var button=$(this);var form=button.closest("form.cart");
var data=form.serialize();if(button.closest(".wonder-wooquickview-addtocart-ajax").hasClass("wonder-wooquickview-addtocart-simple"))data+="&add-to-cart="+form.find("button[name=add-to-cart]").val();button.removeClass("added");button.addClass("loading");$(document.body).trigger("adding_to_cart");$.post(woocommerce_params.wc_ajax_url.toString().replace("%%endpoint%%","get_refreshed_fragments"),data,function(response){if(response&&response.fragments){$.each(response.fragments,function(key,value){$(key).replaceWith(value)});
if(form.find(".added_to_cart").length<=0)button.after(" <a"+(options.viewcartnewtab?' target="_blank"':"")+' href="'+wc_add_to_cart_params.cart_url+'" class="added_to_cart wc-forward" title="'+wc_add_to_cart_params.i18n_view_cart+'">'+wc_add_to_cart_params.i18n_view_cart+"</a>");$(document.body).trigger("wc_fragments_refreshed")}}).done(function(){$(document.body).trigger("added_to_cart")}).always(function(){button.addClass("added");button.removeClass("loading")})})};ajaxAddToCart();var initSlider=
function(){$(".wonder-wooquickview-content-slider").each(function(){var directionNav=$(this).find(".slides").find("li").length>1;$(this).flexslider({animation:"slide",controlNav:"thumbnails",directionNav:directionNav,prevText:'<span class="dashicons dashicons-arrow-left-alt2"></span>',nextText:'<span class="dashicons dashicons-arrow-right-alt2"></span>'})});$(window).on("html5lightbox.lightboxopened",function(){var slider=$("#wonderwoo-lightbox .wonder-wooquickview-content-slider");if(slider.length&&
slider.data("flexslider"))slider.data("flexslider").resize()})};initSlider();var initExtraOptions=function(){if(options.closeafteraddtocart)$(document.body).on("added_to_cart",function(){if(typeof wonderWooLightboxObject!="undefined"&&wonderWooLightboxObject&&wonderWooLightboxObject.$lightbox)wonderWooLightboxObject.finish()})};initExtraOptions()})()})})(jQuery);
